endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

spring:
  application:
    # IDENTITY (ContextIdApplicationContextInitializer)
    name: Resource Service
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:aqueteron
    username: aqueteron
  h2:
    console:
      enabled: true
  jackson.default-property-inclusion: NON_NULL
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  output:
    ansi:
      enabled: always
  profiles:
    active: none