endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

spring:
  application:
    # IDENTITY (ContextIdApplicationContextInitializer)
    name: Resource Service
  jackson.default-property-inclusion: NON_NULL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:aqueteron
    username: aqueteron
  h2:
    console:
      enabled: true

server:
  port: 9090
  # Spring MVC dispatcher servlet path. Needs to be different than Jersey's to enable/disable Actuator endpoints access (/info, /health, ...)
  servlet.path: /