logging.level.org.hibernate.SQL: warn

endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

spring:
  application:
    # IDENTITY (ContextIdApplicationContextInitializer)
    name: Resource Service
  jackson.default-property-inclusion: NON_NULL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  profiles:
    active: profileOne
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:aqueteron
    username: aqueteron
  h2:
    console:
      enabled: true